// File generated by FlutterFire CLI.

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQaUfr9Oxky9dyDjhonTTMWwaUefoBBdk',
    appId: '1:1014328533077:web:5e96a934ed0856287534dc',
    messagingSenderId: '1014328533077',
    projectId: 'appinventario-de2e8',
    authDomain: 'appinventario-de2e8.firebaseapp.com',
    storageBucket: 'appinventario-de2e8.firebasestorage.app',
    measurementId: 'G-SQLDVP35ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGosmJK2dZUzFErTAG9JwiaYM_tUXvTuU',
    appId: '1:1014328533077:android:a4b0c5c41dd176a57534dc',
    messagingSenderId: '1014328533077',
    projectId: 'appinventario-de2e8',
    storageBucket: 'appinventario-de2e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmCzc-QBzNbVbovJMrsmz6yP-jk7i38O8',
    appId: '1:1014328533077:ios:d9acb4409898918e7534dc',
    messagingSenderId: '1014328533077',
    projectId: 'appinventario-de2e8',
    storageBucket: 'appinventario-de2e8.firebasestorage.app',
    iosClientId: '1014328533077-g0i3ksj8titc8hrj7brmd3j8ca18d7ks.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmCzc-QBzNbVbovJMrsmz6yP-jk7i38O8',
    appId: '1:1014328533077:ios:d9acb4409898918e7534dc',
    messagingSenderId: '1014328533077',
    projectId: 'appinventario-de2e8',
    storageBucket: 'appinventario-de2e8.firebasestorage.app',
    iosClientId: '1014328533077-g0i3ksj8titc8hrj7brmd3j8ca18d7ks.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQaUfr9Oxky9dyDjhonTTMWwaUefoBBdk',
    appId: '1:1014328533077:web:5e96a934ed0856287534dc',
    messagingSenderId: '1014328533077',
    projectId: 'appinventario-de2e8',
    authDomain: 'appinventario-de2e8.firebaseapp.com',
    storageBucket: 'appinventario-de2e8.firebasestorage.app',
    measurementId: 'G-SQLDVP35ZJ',
  );

  hola_mundo() {
    print("Hola Mundo");
  }
}

hola_mundo() {
  print("Hola Mundo");
}

asd() {
  print("asd");
}